### ISSUE TITLE
Error in running the plugin

### ISSUE THREAD

**Issue by pcav** [geodrinx/gaeta#2]
Traceback (most recent call last):
  File "/home/paolo/.qgis2/python/plugins/gaeta/gaeta.py", line 1378, in run
    GDX_Publisher(self)
  File "/home/paolo/.qgis2/python/plugins/gaeta/gaeta.py", line 101, in GDX_Publisher
    kml = codecs.open(out_folder + '/gaetaDoc.kml', 'w', encoding='utf-8')
  File "/usr/lib/python2.7/codecs.py", line 896, in open
    file = **builtin**.open(filename, mode, buffering)
IOError: [Errno 2] File o directory non esistente: u'/home/paolo/.qgis2//python/plugins/gaeta/_WebServer/cesium/Apps/cesiumViewer//gaetaDoc.kml'

**Comment by geodrinx** [comment]
Question:  is really "non esistente" this folder on your machine:

/home/paolo/.qgis2//python/plugins/gaeta/_WebServer/cesium/Apps/cesiumViewer//

Question 2:  there is no    "gaetaDoc.kml"   file inside ?

Question 3: perhaps is that folder read only on Linux ? 

Thank you

**Comment by pcav** [comment]
Wrong path; I have:

/home/paolo/.qgis2/python/plugins/gaeta/_WebServer/cesium/

**Comment by geodrinx** [comment]
and inside cesium  folder  there is no  Apps/  and other subfolders ?

**Comment by pcav** [comment]
ls -l /home/paolo/.qgis2/python/plugins/gaeta/_WebServer/cesium/
totale 256
drwxr-xr-x 3 paolo paolo   4096 mar  9 10:41 Apps
-rw-r--r-- 1 paolo paolo 192486 mar  9 10:41 CHANGES.md
-rw-r--r-- 1 paolo paolo     13 mar  9 10:41 descript.ion
-rw-r--r-- 1 paolo paolo  36807 mar  9 10:41 LICENSE.md
-rw-r--r-- 1 paolo paolo  17710 mar  9 10:41 logo.png
drwxr-xr-x 7 paolo paolo   4096 mar  9 10:41 ThirdParty

**Comment by geodrinx** [comment]
Fixed:    problem was  the double //  in the path.

I uploaded a new zip.
